// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhoopL1cToFoSEAl4qol9pcoUuAF65m_s',
    appId: '1:949501863944:web:a7d65a84aee7c6731a49bd',
    messagingSenderId: '949501863944',
    projectId: 'task-kit-1f2d8',
    authDomain: 'task-kit-1f2d8.firebaseapp.com',
    storageBucket: 'task-kit-1f2d8.firebasestorage.app',
    measurementId: 'G-S2XENVF9J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzZB1ZSjJrd4QTzS3cHVDBaV_CUAqpCE',
    appId: '1:949501863944:android:0227da39214adca31a49bd',
    messagingSenderId: '949501863944',
    projectId: 'task-kit-1f2d8',
    storageBucket: 'task-kit-1f2d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb92B_RrWR-KRbMOhnx-JRiCY_lCmgWJk',
    appId: '1:949501863944:ios:98af0187e96d91341a49bd',
    messagingSenderId: '949501863944',
    projectId: 'task-kit-1f2d8',
    storageBucket: 'task-kit-1f2d8.firebasestorage.app',
    iosBundleId: 'com.todo.taskkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb92B_RrWR-KRbMOhnx-JRiCY_lCmgWJk',
    appId: '1:949501863944:ios:98af0187e96d91341a49bd',
    messagingSenderId: '949501863944',
    projectId: 'task-kit-1f2d8',
    storageBucket: 'task-kit-1f2d8.firebasestorage.app',
    iosBundleId: 'com.todo.taskkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhoopL1cToFoSEAl4qol9pcoUuAF65m_s',
    appId: '1:949501863944:web:931f3283c6d2764b1a49bd',
    messagingSenderId: '949501863944',
    projectId: 'task-kit-1f2d8',
    authDomain: 'task-kit-1f2d8.firebaseapp.com',
    storageBucket: 'task-kit-1f2d8.firebasestorage.app',
    measurementId: 'G-DBSGPW8LDH',
  );

}